services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - mqtt-network

  fuseki:
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin123
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki-data:/fuseki
    networks:
      - fuseki-network

  sensor_simulator:
    build: ./sensorSimulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
      - MQTT_TOPIC=sensors/data
    networks:
      - mqtt-network

  semantic_mapper:
    build: ./semanticMapper
    depends_on:
      - mosquitto
      - fuseki
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
      - FUSEKI_URL=http://fuseki:3030
      - MQTT_CLIENT=semantic_mapper
      - MQTT_TOPIC=sensors/data
      - TRIPLESTORE_URL=http://fuseki:3030
      - TRIPLESTORE_DATASET=swot
      - TRIPLESTORE_USERNAME=admin
      - TRIPLESTORE_PASSWORD=admin123
    networks:
      - fuseki-network
      - mqtt-network

  semantic_reasoner:
    build: ./semanticReasoner
    depends_on:
      - fuseki

  api_gateway:
    build: ./apiGateway
    ports:
      - "8080:8080"
    depends_on:
      - fuseki

  visualization:
    build: ./visualization
    ports:
      - "8081:8081"
    depends_on:
      - api_gateway

networks:
  mqtt-network:
    driver: bridge
  fuseki-network:
    driver: bridge