services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # Contraseña del usuario root
      MYSQL_DATABASE: nursing_home_db                    # Nombre de la base de datos
      MYSQL_USER: myuser                      # Usuario adicional
      MYSQL_PASSWORD: mypassword    
    networks:
      - mysql-network        # Contraseña del usuario adicional
  jena:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jena/data:/fuseki
    environment:
      - ADMIN_PASSWORD=Oe8AUz9xPHbdskvn
    networks:
      - jena-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass superpass --appendonly yes
    networks:
      - redis-network
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - mosquitto-network
  sensors:
    build: ./sensors
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - LOG_LEVEL=INFO
    depends_on:
      - mosquitto
    networks:
      - mosquitto-network
  mapper:
    build: ./mapper
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=nursing_home_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=superpass
      - JENA_HOST=http://jena:3030
      - JENA_DATASET=nursing-home
      - JENA_USER=admin
      - JENA_PASSWORD=Oe8AUz9xPHbdskvn
      - SENSORS_TOPIC=nursing-home/sensors
      - ACTUATOR_STATE_TOPIC=nursing-home/actuators/state
      - ACTUATOR_STATE_REQUEST_TOPIC=nursing-home/actuators/state/request
      - SEMANTIC_SENSOR_TOPIC=nursing-home/semantic/sensors
      - SEMANTIC_ACTUATOR_TOPIC=nursing-home/semantic/actuators
      - LOG_LEVEL=INFO
    depends_on:
      - jena
      - mysql
      - redis
      - mosquitto
    networks:
      - jena-network
      - mysql-network
      - redis-network
      - mosquitto-network

  reasoner:
    build: ./reasoner
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - JENA_HOST=http://jena:3030
      - JENA_DATASET=nursing-home
      - JENA_USER=admin
      - JENA_PASSWORD=Oe8AUz9xPHbdskvn
      - SEMANTIC_SENSOR_TOPIC=nursing-home/semantic/sensors
      - SEMANTIC_ACTUATOR_TOPIC=nursing-home/semantic/actuators
      - LOG_LEVEL=INFO
    depends_on:
      - mapper
    networks:
      - jena-network
      - mosquitto-network

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - JENA_HOST=http://jena:3030
      - JENA_DATASET=nursing-home
      - JENA_USER=admin
      - JENA_PASSWORD=Oe8AUz9xPHbdskvn
      - SEMANTIC_SENSOR_TOPIC=nursing-home/semantic/sensors
      - SEMANTIC_ACTUATOR_TOPIC=nursing-home/semantic/actuators
    depends_on:
      - mapper
    networks:
      - api-network
      - jena-network
      - mosquitto-network
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - HOSTNAME=0.0.0.0
    networks:
      - api-network


networks:
  mysql-network:
    driver: bridge
  redis-network:
    driver: bridge
  mosquitto-network:
    driver: bridge
  jena-network:
    driver: bridge
  api-network:
    driver: bridge